# File: .github/workflows/repo-sync.yml

on:
  push:
    branches:
    - dell
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      #    - uses: actions/checkout@v2
    - name: git-sync
      uses: wei/git-sync@v3
      with:
        source_repo: "gody48/dummy"
        source_branch: "dell"
        destination_repo: "gody48/dummy1"
        destination_branch: "dell"
#        github_token: ${{ secrets.PAT }}
